# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 802)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_preview = QtWidgets.QWidget()
        self.tab_preview.setObjectName("tab_preview")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_preview)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.wgtDisplayArea = QtImageViewer()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtDisplayArea.sizePolicy().hasHeightForWidth())
        self.wgtDisplayArea.setSizePolicy(sizePolicy)
        self.wgtDisplayArea.setMinimumSize(QtCore.QSize(425, 600))
        self.wgtDisplayArea.setObjectName("wgtDisplayArea")
        self.horizontalLayout_8.addWidget(self.wgtDisplayArea)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_msg_image_name = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_msg_image_name.sizePolicy().hasHeightForWidth())
        self.lbl_msg_image_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_msg_image_name.setFont(font)
        self.lbl_msg_image_name.setObjectName("lbl_msg_image_name")
        self.horizontalLayout_2.addWidget(self.lbl_msg_image_name)
        self.lbl_image_name = QtWidgets.QLabel(self.tab_preview)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_image_name.setFont(font)
        self.lbl_image_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_image_name.setText("")
        self.lbl_image_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_image_name.setObjectName("lbl_image_name")
        self.horizontalLayout_2.addWidget(self.lbl_image_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_image_path_ui = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image_path_ui.sizePolicy().hasHeightForWidth())
        self.lbl_image_path_ui.setSizePolicy(sizePolicy)
        self.lbl_image_path_ui.setMinimumSize(QtCore.QSize(30, 0))
        self.lbl_image_path_ui.setObjectName("lbl_image_path_ui")
        self.horizontalLayout_3.addWidget(self.lbl_image_path_ui)
        self.lbl_image_path = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_image_path.sizePolicy().hasHeightForWidth())
        self.lbl_image_path.setSizePolicy(sizePolicy)
        self.lbl_image_path.setMinimumSize(QtCore.QSize(470, 0))
        self.lbl_image_path.setText("")
        self.lbl_image_path.setObjectName("lbl_image_path")
        self.horizontalLayout_3.addWidget(self.lbl_image_path)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLoadImage = QtWidgets.QPushButton(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLoadImage.sizePolicy().hasHeightForWidth())
        self.btnLoadImage.setSizePolicy(sizePolicy)
        self.btnLoadImage.setMinimumSize(QtCore.QSize(60, 60))
        self.btnLoadImage.setObjectName("btnLoadImage")
        self.horizontalLayout.addWidget(self.btnLoadImage)
        self.btnSaveImages = QtWidgets.QPushButton(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveImages.sizePolicy().hasHeightForWidth())
        self.btnSaveImages.setSizePolicy(sizePolicy)
        self.btnSaveImages.setMinimumSize(QtCore.QSize(60, 60))
        self.btnSaveImages.setObjectName("btnSaveImages")
        self.horizontalLayout.addWidget(self.btnSaveImages)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lbl_msg_areas_saved = QtWidgets.QLabel(self.tab_preview)
        self.lbl_msg_areas_saved.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_msg_areas_saved.setFont(font)
        self.lbl_msg_areas_saved.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_msg_areas_saved.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_msg_areas_saved.setObjectName("lbl_msg_areas_saved")
        self.verticalLayout_2.addWidget(self.lbl_msg_areas_saved)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_msg_anomaly = QtWidgets.QLabel(self.tab_preview)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_msg_anomaly.setFont(font)
        self.lbl_msg_anomaly.setObjectName("lbl_msg_anomaly")
        self.horizontalLayout_5.addWidget(self.lbl_msg_anomaly)
        spacerItem3 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.chb_anomaly = QtWidgets.QCheckBox(self.tab_preview)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chb_anomaly.setFont(font)
        self.chb_anomaly.setChecked(True)
        self.chb_anomaly.setObjectName("chb_anomaly")
        self.horizontalLayout_5.addWidget(self.chb_anomaly)
        self.label_4 = QtWidgets.QLabel(self.tab_preview)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wgtDisplayPreview = QtImageViewer()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgtDisplayPreview.sizePolicy().hasHeightForWidth())
        self.wgtDisplayPreview.setSizePolicy(sizePolicy)
        self.wgtDisplayPreview.setMinimumSize(QtCore.QSize(250, 250))
        self.wgtDisplayPreview.setObjectName("wgtDisplayPreview")
        self.horizontalLayout_4.addWidget(self.wgtDisplayPreview)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_msg_list_points_tab1 = QtWidgets.QLabel(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_msg_list_points_tab1.sizePolicy().hasHeightForWidth())
        self.lbl_msg_list_points_tab1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lbl_msg_list_points_tab1.setFont(font)
        self.lbl_msg_list_points_tab1.setObjectName("lbl_msg_list_points_tab1")
        self.verticalLayout_3.addWidget(self.lbl_msg_list_points_tab1)
        self.lst_selected_points = QtWidgets.QListWidget(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_selected_points.sizePolicy().hasHeightForWidth())
        self.lst_selected_points.setSizePolicy(sizePolicy)
        self.lst_selected_points.setMinimumSize(QtCore.QSize(50, 100))
        self.lst_selected_points.setObjectName("lst_selected_points")
        self.verticalLayout_3.addWidget(self.lst_selected_points)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.lbl_point_description = QtWidgets.QLabel(self.tab_preview)
        self.lbl_point_description.setObjectName("lbl_point_description")
        self.verticalLayout_2.addWidget(self.lbl_point_description)
        self.box_point_description = QtWidgets.QPlainTextEdit(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_point_description.sizePolicy().hasHeightForWidth())
        self.box_point_description.setSizePolicy(sizePolicy)
        self.box_point_description.setMinimumSize(QtCore.QSize(0, 31))
        self.box_point_description.setMaximumSize(QtCore.QSize(16777215, 60))
        self.box_point_description.setObjectName("box_point_description")
        self.verticalLayout_2.addWidget(self.box_point_description)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.btn_rst_points = QtWidgets.QPushButton(self.tab_preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_rst_points.sizePolicy().hasHeightForWidth())
        self.btn_rst_points.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_rst_points.setFont(font)
        self.btn_rst_points.setObjectName("btn_rst_points")
        self.verticalLayout_2.addWidget(self.btn_rst_points)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_preview, "")
        self.tab_list_info = QtWidgets.QWidget()
        self.tab_list_info.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tab_list_info.setObjectName("tab_list_info")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_list_info)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.treeFiles = QtWidgets.QTreeWidget(self.tab_list_info)
        self.treeFiles.setObjectName("treeFiles")
        self.horizontalLayout_6.addWidget(self.treeFiles)
        self.treeSelPoints = QtWidgets.QTreeWidget(self.tab_list_info)
        self.treeSelPoints.setObjectName("treeSelPoints")
        self.horizontalLayout_6.addWidget(self.treeSelPoints)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_sel_dir = QtWidgets.QPushButton(self.tab_list_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sel_dir.sizePolicy().hasHeightForWidth())
        self.btn_sel_dir.setSizePolicy(sizePolicy)
        self.btn_sel_dir.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_sel_dir.setObjectName("btn_sel_dir")
        self.verticalLayout.addWidget(self.btn_sel_dir)
        self.btn_refresh = QtWidgets.QPushButton(self.tab_list_info)
        self.btn_refresh.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_refresh.setObjectName("btn_refresh")
        self.verticalLayout.addWidget(self.btn_refresh)
        self.btn_autorefresh = QtWidgets.QPushButton(self.tab_list_info)
        self.btn_autorefresh.setObjectName("btn_autorefresh")
        self.verticalLayout.addWidget(self.btn_autorefresh)
        self.btn_expand_img = QtWidgets.QPushButton(self.tab_list_info)
        self.btn_expand_img.setObjectName("btn_expand_img")
        self.verticalLayout.addWidget(self.btn_expand_img)
        self.btn_expand_points = QtWidgets.QPushButton(self.tab_list_info)
        self.btn_expand_points.setObjectName("btn_expand_points")
        self.verticalLayout.addWidget(self.btn_expand_points)
        self.btn_gen_dataset = QtWidgets.QPushButton(self.tab_list_info)
        self.btn_gen_dataset.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_gen_dataset.sizePolicy().hasHeightForWidth())
        self.btn_gen_dataset.setSizePolicy(sizePolicy)
        self.btn_gen_dataset.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_gen_dataset.setObjectName("btn_gen_dataset")
        self.verticalLayout.addWidget(self.btn_gen_dataset)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_item_path_ui = QtWidgets.QLabel(self.tab_list_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_item_path_ui.sizePolicy().hasHeightForWidth())
        self.lbl_item_path_ui.setSizePolicy(sizePolicy)
        self.lbl_item_path_ui.setMinimumSize(QtCore.QSize(160, 0))
        self.lbl_item_path_ui.setObjectName("lbl_item_path_ui")
        self.horizontalLayout_7.addWidget(self.lbl_item_path_ui)
        self.lbl_item_path = QtWidgets.QLabel(self.tab_list_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_item_path.sizePolicy().hasHeightForWidth())
        self.lbl_item_path.setSizePolicy(sizePolicy)
        self.lbl_item_path.setText("")
        self.lbl_item_path.setObjectName("lbl_item_path")
        self.horizontalLayout_7.addWidget(self.lbl_item_path)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbl_dir_path_ui = QtWidgets.QLabel(self.tab_list_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_dir_path_ui.sizePolicy().hasHeightForWidth())
        self.lbl_dir_path_ui.setSizePolicy(sizePolicy)
        self.lbl_dir_path_ui.setMinimumSize(QtCore.QSize(160, 0))
        self.lbl_dir_path_ui.setObjectName("lbl_dir_path_ui")
        self.horizontalLayout_9.addWidget(self.lbl_dir_path_ui)
        self.lbl_dir_path = QtWidgets.QLabel(self.tab_list_info)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_dir_path.sizePolicy().hasHeightForWidth())
        self.lbl_dir_path.setSizePolicy(sizePolicy)
        self.lbl_dir_path.setText("")
        self.lbl_dir_path.setObjectName("lbl_dir_path")
        self.horizontalLayout_9.addWidget(self.lbl_dir_path)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab_list_info, "")
        self.tab_preprocessing = QtWidgets.QWidget()
        self.tab_preprocessing.setEnabled(False)
        self.tab_preprocessing.setObjectName("tab_preprocessing")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_preprocessing)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 50, 171, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_msg_roi_height = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_msg_roi_height.setObjectName("lbl_msg_roi_height")
        self.gridLayout_2.addWidget(self.lbl_msg_roi_height, 0, 0, 1, 1)
        self.lbl_msg_roi_width = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_msg_roi_width.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_msg_roi_width.setObjectName("lbl_msg_roi_width")
        self.gridLayout_2.addWidget(self.lbl_msg_roi_width, 1, 0, 1, 1)
        self.in_roi_height = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.in_roi_height.setObjectName("in_roi_height")
        self.gridLayout_2.addWidget(self.in_roi_height, 0, 1, 1, 1)
        self.in_roi_width = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.in_roi_width.setObjectName("in_roi_width")
        self.gridLayout_2.addWidget(self.in_roi_width, 1, 1, 1, 1)
        self.lbl_msg_roi_info = QtWidgets.QLabel(self.tab_preprocessing)
        self.lbl_msg_roi_info.setGeometry(QtCore.QRect(20, 20, 161, 20))
        self.lbl_msg_roi_info.setObjectName("lbl_msg_roi_info")
        self.tabWidget.addTab(self.tab_preprocessing, "")
        self.tab_help = QtWidgets.QWidget()
        self.tab_help.setObjectName("tab_help")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_help)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.box_help_info = QtWidgets.QPlainTextEdit(self.tab_help)
        self.box_help_info.setEnabled(True)
        self.box_help_info.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.box_help_info.setObjectName("box_help_info")
        self.verticalLayout_6.addWidget(self.box_help_info)
        self.tabWidget.addTab(self.tab_help, "")
        self.tab_credits = QtWidgets.QWidget()
        self.tab_credits.setObjectName("tab_credits")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_credits)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem8)
        self.lbl_img_uv = QtWidgets.QLabel(self.tab_credits)
        self.lbl_img_uv.setText("")
        self.lbl_img_uv.setPixmap(QtGui.QPixmap("../img_app/logo_uv_scaled.jpg"))
        self.lbl_img_uv.setObjectName("lbl_img_uv")
        self.horizontalLayout_10.addWidget(self.lbl_img_uv)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.lb_img_uv = QtWidgets.QLabel(self.tab_credits)
        self.lb_img_uv.setText("")
        self.lb_img_uv.setPixmap(QtGui.QPixmap("../img_app/logo_etse_3.png"))
        self.lb_img_uv.setObjectName("lb_img_uv")
        self.horizontalLayout_10.addWidget(self.lb_img_uv)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.lb_img_gpdd = QtWidgets.QLabel(self.tab_credits)
        self.lb_img_gpdd.setText("")
        self.lb_img_gpdd.setPixmap(QtGui.QPixmap("../img_app/logo_gpdd.png"))
        self.lb_img_gpdd.setObjectName("lb_img_gpdd")
        self.verticalLayout_7.addWidget(self.lb_img_gpdd)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.lb_help_contact = QtWidgets.QLabel(self.tab_credits)
        self.lb_help_contact.setObjectName("lb_help_contact")
        self.horizontalLayout_11.addWidget(self.lb_help_contact)
        spacerItem12 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem12)
        self.label = QtWidgets.QLabel(self.tab_credits)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_credits, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 25))
        self.menubar.setObjectName("menubar")
        self.menuMain_Menu = QtWidgets.QMenu(self.menubar)
        self.menuMain_Menu.setObjectName("menuMain_Menu")
        self.menuCredits = QtWidgets.QMenu(self.menubar)
        self.menuCredits.setObjectName("menuCredits")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionSave_Sthg = QtWidgets.QAction(MainWindow)
        self.actionSave_Sthg.setObjectName("actionSave_Sthg")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.menuMain_Menu.addSeparator()
        self.menuMain_Menu.addAction(self.actionClose)
        self.menubar.addAction(self.menuMain_Menu.menuAction())
        self.menubar.addAction(self.menuCredits.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hyperspectral Labeling Tool v1.0"))
        self.lbl_msg_image_name.setText(_translate("MainWindow", "Image:"))
        self.lbl_image_path_ui.setText(_translate("MainWindow", "Path:"))
        self.btnLoadImage.setText(_translate("MainWindow", "Load \".tif\" Image "))
        self.btnSaveImages.setText(_translate("MainWindow", "Save Selected Areas"))
        self.lbl_msg_areas_saved.setText(_translate("MainWindow", "TextLabel"))
        self.lbl_msg_anomaly.setText(_translate("MainWindow", "Current selection area:"))
        self.chb_anomaly.setText(_translate("MainWindow", "Anomaly"))
        self.lbl_msg_list_points_tab1.setText(_translate("MainWindow", "List of seleccted points  "))
        self.lbl_point_description.setText(_translate("MainWindow", "Selected point description:"))
        self.btn_rst_points.setText(_translate("MainWindow", "Reset current selected points"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preview), _translate("MainWindow", "Previsualization and Area Selection"))
        self.treeFiles.headerItem().setText(0, _translate("MainWindow", "Available Images"))
        self.treeFiles.headerItem().setText(1, _translate("MainWindow", "Status"))
        self.treeSelPoints.headerItem().setText(0, _translate("MainWindow", "Slected points"))
        self.treeSelPoints.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.btn_sel_dir.setText(_translate("MainWindow", "Directory"))
        self.btn_refresh.setText(_translate("MainWindow", "Refresh"))
        self.btn_autorefresh.setText(_translate("MainWindow", "AutoRefesh ON"))
        self.btn_expand_img.setText(_translate("MainWindow", "Expand Images"))
        self.btn_expand_points.setText(_translate("MainWindow", "Expand points"))
        self.btn_gen_dataset.setText(_translate("MainWindow", "Gen. Dataset"))
        self.lbl_item_path_ui.setText(_translate("MainWindow", "Selected element path:"))
        self.lbl_dir_path_ui.setText(_translate("MainWindow", "Image\'s Directory path:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_list_info), _translate("MainWindow", "List of pre-processed images"))
        self.lbl_msg_roi_height.setText(_translate("MainWindow", "Height: "))
        self.lbl_msg_roi_width.setText(_translate("MainWindow", "Width: "))
        self.lbl_msg_roi_info.setText(_translate("MainWindow", "Region of interest Size:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_preprocessing), _translate("MainWindow", "Preprocessing info"))
        self.box_help_info.setPlainText(_translate("MainWindow", "Ayuda\n"
"-----\n"
"La aplicación se se encuentra constituida principalmente de tres partes organizada en pestañas:\n"
"* Previsualización y área de selección\n"
"* Lista de imágenes preprocesadas \n"
"* Parámetros de preprocesamiento.\n"
"\n"
"[1] Previsualización y área de selección\n"
"\n"
"1.1. Área de visualización de la imagen cargada\n"
"Esta pestaña cuenta con una área de visualización general de la imagen cargada, ubicándose en el lado izquierdo. \n"
"1.1.1 Clic botón izquierdo: movimiento dentro de la imagen con zoom\n"
"1.1.2 Trazar un rectángulo con botón derecho: Zoom en dicha área\n"
"1.1.3 Doble click botón derecho: reestabnlecimiento del zoom original\n"
"1.1.4 Ctrl + click izquierdo: agregado de dicho punto como punto de interés \n"
"\n"
"1.2 Opciones de la pestaña de previsualización y área de selección\n"
"1.2.1 Cargar imagen .tif: permite seleccionar una imagen .tif para ser pre-procesada\n"
"1.2.2 Lista de puntos seleccionados: muestra las coordenadas de los puntos que se van agregando. Cada punto agregado se caracterizará como anómalo (si tienen un defecto) o normal en función si el checkbox está seleccionado o no. Si se desea modificar un punto seleccionad, haciendo click derecho sobre el punto, mostrará diferentes opciones. Importante: una vez salvados los puntos seleccionados, los mismos no pueden ser borrados desde la aplicación, es decir, deberá abrirse el archivo .csv con la informacion y borrarla cuidadosamente.\n"
"1.2.3 Descrición del punto seleccionado: (opcional) es posible agregar una descripción al punto seleccionado.\n"
"1.2.4 Reseteo de los puntos seleccionados: borra todos los puntos seleccionados que no han sido guardados.\n"
"\n"
"[2] Lista de imágenes preprocesadas\n"
"El objetivo de esta pesataña es comparar el estado actual del trabajo y de esta manera tener una imagen clara de qué imágenes restan por ser pre-procesadas. La aplicacion compara las imágenes de un directorio determinado, con los puntos guardados en la base de datos.\n"
"2.1 Botones:\n"
"2.1.1 Botón directorio: permite seleccionar el directorio padre donde se buscarán todas las imágenes. A su vez, si este directorio es seleccionado, también permitirá buscar más rápido las imágenes cuando se opere en la primer pestaña descripta en [1].\n"
"2.1.2 Botón Refrescar: actualiza tanto las imágenes buscada, como los puntos guardados por si ha habido alún cambio.\n"
"2.1.3 Botón Auto-refresco ON: cambian entre encendido/apagado el modo de auto refresco, dado que el mismo, si se encuentra encendido dejará completamente extendido o contraido ambos árboles de información según esté seleccionado en 2.4 y 2.5\n"
"2.1.4 Expandir/Contraer Imágenes: expande/contrae la visualización mostrando los puntos seleccionados para las imágenes encontradas\n"
"2.1.5 Expandir/Contraer Puntos: expande/contrae la visualización mostrando los puntos almacenados seleccionados\n"
"\n"
"2.2 Barra de direcciones:\n"
"2.2.1 Dirección del elemento seleccionado: si se hace click izquierdo sobre cualquier imagen, se visualizarará la dirección del elemento seleccionado.\n"
"2.2.2 Dirección del directorio de imágenes: muestra la dirección la dirección del directorio seleccionado desde el botón 2.1.1 para llevar a cabo la búsqueda de imágenes\n"
"\n"
"[3] Información de pre-procesado:\n"
"Pestaña empleada para generar un dataset. \n"
"\n"
"Todos los elementos deshabilitados son elementos no necesarios al momento de llevar a cabo el etiquetado de las imágenes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_help), _translate("MainWindow", "Help"))
        self.lb_help_contact.setText(_translate("MainWindow", "GPDD (Grupo de Procesado y Diseño Digitales)\n"
"\n"
"Departament d\'Enginyería Electrònica.\n"
" Escola Técnica Superior d\'Enginyería (ETSE)\n"
"Universitat de València-Estudi General\n"
"Avda. Universitat, s/n\n"
"E-46100 Burjassot (València)\n"
"ESPAÑA\n"
"Tel: +34 96 35 44032\n"
"Fax: +34 96 35 44353"))
        self.label.setText(_translate("MainWindow", "Contacto:\n"
"\n"
"Leandro Medus\n"
"leandro.d.medus@uv.es"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_credits), _translate("MainWindow", "Credits"))
        self.menuMain_Menu.setTitle(_translate("MainWindow", "Main Menu"))
        self.menuCredits.setTitle(_translate("MainWindow", "Info"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionSave_Sthg.setText(_translate("MainWindow", "Save Sthg"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))

from PyQtImageViewer.QtImageViewer import QtImageViewer

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

